apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - hpe/bios-ref-hpe-proliant-dl110-master.yaml
  - hpe/bios-ref-hpe-proliant-dl110-worker.yaml
  - hpe/bios-ref-hpe-proliant-e910t-master.yaml
  - hpe/bios-ref-hpe-proliant-e910t-worker.yaml
  - dell/bios-ref-dell-xr8620t-master.yaml
  - dell/bios-ref-dell-xr8620t-worker.yaml
